[package]
name = "supurge"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

eframe = {version = "0.29.0"}
egui_plot = "0.29.0"
macroquad = {version = "*"}


image = { version = "*", features = ["png"] }
rfd = "0.13.0"